FROM php:8.2-apache

# Instalación de extensiones
RUN docker-php-ext-install pdo pdo_mysql

# Copiar archivos del backend
COPY ./api /var/www/html/api

# Copiar archivos del frontend PHP
COPY ./public/ /var/www/html/

# Exponer puerto del servidor web
EXPOSE 80
