FROM php:8.2-apache

# Instalación de extensiones
RUN docker-php-ext-install pdo pdo_mysql

# Copiar archivos
COPY ./api /var/www/html/api
COPY ./public /var/www/html/public

# Exponer puerto
EXPOSE 80